FROM node:18-alpine

WORKDIR /app/apps/web

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

COPY apps/web/package*.json ./
RUN npm ci --prefer-offline --no-audit

COPY apps/web ./
RUN npm run build

EXPOSE 3000

CMD ["npm", "start", "--", "-p", "3000"]
